name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Запуск каждый день в 00:00 UTC
  workflow_dispatch: # Возможность запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Добавляем разрешение на запись
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: NeoRassinin
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg
      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
